# Generated by Django 4.0.1 on 2022-01-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='surname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
